#pragma once

#include <optional>

#include "sc2api/sc2_agent.h"
#include "sc2api/sc2_interfaces.h"
#include "sc2api/sc2_map_info.h"
#include "sc2lib/sc2_utils.h"

namespace sc2 {
	struct StaticUnitInfo {
		std::optional<UNIT_TYPEID> required_building;
		ABILITY_ID creation_ability;
		bool requires_techlab;
		bool requires_placement_position;
		bool requires_power;
	};



	constexpr inline bool is_building(UNIT_TYPEID type_) {
		switch (type_) {
			// Terran
		case UNIT_TYPEID::TERRAN_ARMORY:
		case UNIT_TYPEID::TERRAN_BARRACKS:
		case UNIT_TYPEID::TERRAN_BARRACKSFLYING:
		case UNIT_TYPEID::TERRAN_BARRACKSREACTOR:
		case UNIT_TYPEID::TERRAN_BARRACKSTECHLAB:
		case UNIT_TYPEID::TERRAN_BUNKER:
		case UNIT_TYPEID::TERRAN_COMMANDCENTER:
		case UNIT_TYPEID::TERRAN_COMMANDCENTERFLYING:
		case UNIT_TYPEID::TERRAN_ENGINEERINGBAY:
		case UNIT_TYPEID::TERRAN_FACTORY:
		case UNIT_TYPEID::TERRAN_FACTORYFLYING:
		case UNIT_TYPEID::TERRAN_FACTORYREACTOR:
		case UNIT_TYPEID::TERRAN_FACTORYTECHLAB:
		case UNIT_TYPEID::TERRAN_FUSIONCORE:
		case UNIT_TYPEID::TERRAN_GHOSTACADEMY:
		case UNIT_TYPEID::TERRAN_MISSILETURRET:
		case UNIT_TYPEID::TERRAN_ORBITALCOMMAND:
		case UNIT_TYPEID::TERRAN_ORBITALCOMMANDFLYING:
		case UNIT_TYPEID::TERRAN_PLANETARYFORTRESS:
		case UNIT_TYPEID::TERRAN_REFINERY:
		case UNIT_TYPEID::TERRAN_SENSORTOWER:
		case UNIT_TYPEID::TERRAN_STARPORT:
		case UNIT_TYPEID::TERRAN_STARPORTFLYING:
		case UNIT_TYPEID::TERRAN_STARPORTREACTOR:
		case UNIT_TYPEID::TERRAN_STARPORTTECHLAB:
		case UNIT_TYPEID::TERRAN_SUPPLYDEPOT:
		case UNIT_TYPEID::TERRAN_SUPPLYDEPOTLOWERED:
		case UNIT_TYPEID::TERRAN_REACTOR:
		case UNIT_TYPEID::TERRAN_TECHLAB:

			// Zerg
		case UNIT_TYPEID::ZERG_BANELINGNEST:
		case UNIT_TYPEID::ZERG_CREEPTUMOR:
		case UNIT_TYPEID::ZERG_CREEPTUMORBURROWED:
		case UNIT_TYPEID::ZERG_CREEPTUMORQUEEN:
		case UNIT_TYPEID::ZERG_EVOLUTIONCHAMBER:
		case UNIT_TYPEID::ZERG_EXTRACTOR:
		case UNIT_TYPEID::ZERG_GREATERSPIRE:
		case UNIT_TYPEID::ZERG_HATCHERY:
		case UNIT_TYPEID::ZERG_HIVE:
		case UNIT_TYPEID::ZERG_HYDRALISKDEN:
		case UNIT_TYPEID::ZERG_INFESTATIONPIT:
		case UNIT_TYPEID::ZERG_LAIR:
		case UNIT_TYPEID::ZERG_LURKERDENMP:
		case UNIT_TYPEID::ZERG_NYDUSCANAL:
		case UNIT_TYPEID::ZERG_NYDUSNETWORK:
		case UNIT_TYPEID::ZERG_ROACHWARREN:
		case UNIT_TYPEID::ZERG_SPAWNINGPOOL:
		case UNIT_TYPEID::ZERG_SPINECRAWLER:
		case UNIT_TYPEID::ZERG_SPINECRAWLERUPROOTED:
		case UNIT_TYPEID::ZERG_SPIRE:
		case UNIT_TYPEID::ZERG_SPORECRAWLER:
		case UNIT_TYPEID::ZERG_SPORECRAWLERUPROOTED:
		case UNIT_TYPEID::ZERG_ULTRALISKCAVERN:

			// Protoss
		case sc2::UNIT_TYPEID::PROTOSS_ASSIMILATOR:
		case sc2::UNIT_TYPEID::PROTOSS_CYBERNETICSCORE:
		case sc2::UNIT_TYPEID::PROTOSS_DARKSHRINE:
		case sc2::UNIT_TYPEID::PROTOSS_FLEETBEACON:
		case sc2::UNIT_TYPEID::PROTOSS_FORGE:
		case sc2::UNIT_TYPEID::PROTOSS_GATEWAY:
		case sc2::UNIT_TYPEID::PROTOSS_NEXUS:
		case sc2::UNIT_TYPEID::PROTOSS_PHOTONCANNON:
		case sc2::UNIT_TYPEID::PROTOSS_PYLON:
		case sc2::UNIT_TYPEID::PROTOSS_PYLONOVERCHARGED:
		case sc2::UNIT_TYPEID::PROTOSS_ROBOTICSBAY:
		case sc2::UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY:
		case sc2::UNIT_TYPEID::PROTOSS_STARGATE:
		case sc2::UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE:
		case sc2::UNIT_TYPEID::PROTOSS_TWILIGHTCOUNCIL:
		case sc2::UNIT_TYPEID::PROTOSS_WARPGATE:
		case sc2::UNIT_TYPEID::PROTOSS_SHIELDBATTERY:
			return true;

		default:
			return false;
		}
	}

	constexpr inline bool is_building(const Unit& unit_) {
		return is_building(unit_.unit_type);
	}


	constexpr inline std::vector<UNIT_TYPEID> unit_trained_from(UNIT_TYPEID unit) {
		switch (unit)
		{
		case UNIT_TYPEID::PROTOSS_ADEPT: return { UNIT_TYPEID::PROTOSS_GATEWAY, UNIT_TYPEID::PROTOSS_WARPGATE };
		case UNIT_TYPEID::TERRAN_ARMORY: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::PROTOSS_ASSIMILATOR: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_AUTOTURRET: return { UNIT_TYPEID::TERRAN_RAVEN };
		case UNIT_TYPEID::ZERG_BANELING: return { UNIT_TYPEID::ZERG_ZERGLING };
		case UNIT_TYPEID::ZERG_BANELINGNEST: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::TERRAN_BANSHEE: return { UNIT_TYPEID::TERRAN_STARPORT };
		case UNIT_TYPEID::TERRAN_BARRACKS: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::TERRAN_BATTLECRUISER: return { UNIT_TYPEID::TERRAN_STARPORT };
		case UNIT_TYPEID::ZERG_BROODLORD: return { UNIT_TYPEID::ZERG_CORRUPTOR };
		case UNIT_TYPEID::TERRAN_BUNKER: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::PROTOSS_CARRIER: return { UNIT_TYPEID::PROTOSS_STARGATE };
		case UNIT_TYPEID::ZERG_CHANGELING: return { UNIT_TYPEID::ZERG_OVERSEER, UNIT_TYPEID::ZERG_OVERSEERSIEGEMODE };
		case UNIT_TYPEID::PROTOSS_COLOSSUS: return { UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY };
		case UNIT_TYPEID::TERRAN_COMMANDCENTER: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::ZERG_CORRUPTOR: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::ZERG_CREEPTUMOR: return { UNIT_TYPEID::ZERG_CREEPTUMOR, UNIT_TYPEID::ZERG_CREEPTUMORBURROWED, UNIT_TYPEID::ZERG_QUEEN };
		case UNIT_TYPEID::ZERG_CREEPTUMORQUEEN: return { UNIT_TYPEID::ZERG_QUEEN };
		case UNIT_TYPEID::PROTOSS_CYBERNETICSCORE: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_CYCLONE: return { UNIT_TYPEID::TERRAN_FACTORY };
		case UNIT_TYPEID::PROTOSS_DARKSHRINE: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::PROTOSS_DARKTEMPLAR: return { UNIT_TYPEID::PROTOSS_GATEWAY, UNIT_TYPEID::PROTOSS_WARPGATE };
		case UNIT_TYPEID::PROTOSS_DISRUPTOR: return { UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY };
		case UNIT_TYPEID::ZERG_DRONE: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::TERRAN_ENGINEERINGBAY: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::ZERG_EVOLUTIONCHAMBER: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::ZERG_EXTRACTOR: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::TERRAN_FACTORY: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::PROTOSS_FLEETBEACON: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::PROTOSS_FORGE: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_FUSIONCORE: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::PROTOSS_GATEWAY: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_GHOST: return { UNIT_TYPEID::TERRAN_BARRACKS };
		case UNIT_TYPEID::TERRAN_GHOSTACADEMY: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::ZERG_GREATERSPIRE: return { UNIT_TYPEID::ZERG_SPIRE };
		case UNIT_TYPEID::ZERG_HATCHERY: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::TERRAN_HELLION: return { UNIT_TYPEID::TERRAN_FACTORY };
		case UNIT_TYPEID::TERRAN_HELLIONTANK: return { UNIT_TYPEID::TERRAN_FACTORY };
		case UNIT_TYPEID::PROTOSS_HIGHTEMPLAR: return { UNIT_TYPEID::PROTOSS_GATEWAY, UNIT_TYPEID::PROTOSS_WARPGATE };
		case UNIT_TYPEID::ZERG_HIVE: return { UNIT_TYPEID::ZERG_LAIR };
		case UNIT_TYPEID::ZERG_HYDRALISK: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::ZERG_HYDRALISKDEN: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::PROTOSS_IMMORTAL: return { UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY };
		case UNIT_TYPEID::ZERG_INFESTATIONPIT: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::ZERG_INFESTOR: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::ZERG_LAIR: return { UNIT_TYPEID::ZERG_HATCHERY };
		case UNIT_TYPEID::TERRAN_LIBERATOR: return { UNIT_TYPEID::TERRAN_STARPORT };
		case UNIT_TYPEID::ZERG_LOCUSTMPFLYING: return { UNIT_TYPEID::ZERG_SWARMHOSTBURROWEDMP, UNIT_TYPEID::ZERG_SWARMHOSTMP };
		case UNIT_TYPEID::ZERG_LURKERDENMP: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::ZERG_LURKERMP: return { UNIT_TYPEID::ZERG_HYDRALISK };
		case UNIT_TYPEID::TERRAN_MARAUDER: return { UNIT_TYPEID::TERRAN_BARRACKS };
		case UNIT_TYPEID::TERRAN_MARINE: return { UNIT_TYPEID::TERRAN_BARRACKS };
		case UNIT_TYPEID::TERRAN_MEDIVAC: return { UNIT_TYPEID::TERRAN_STARPORT };
		case UNIT_TYPEID::TERRAN_MISSILETURRET: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::PROTOSS_MOTHERSHIP: return { UNIT_TYPEID::PROTOSS_NEXUS };
		case UNIT_TYPEID::ZERG_MUTALISK: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::PROTOSS_NEXUS: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::ZERG_NYDUSCANAL: return { UNIT_TYPEID::ZERG_NYDUSNETWORK };
		case UNIT_TYPEID::ZERG_NYDUSNETWORK: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::PROTOSS_OBSERVER: return { UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY };
		case UNIT_TYPEID::PROTOSS_ORACLE: return { UNIT_TYPEID::PROTOSS_STARGATE };
		case UNIT_TYPEID::PROTOSS_ORACLESTASISTRAP: return { UNIT_TYPEID::PROTOSS_ORACLE };
		case UNIT_TYPEID::TERRAN_ORBITALCOMMAND: return { UNIT_TYPEID::TERRAN_COMMANDCENTER };
		case UNIT_TYPEID::ZERG_OVERLORD: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::ZERG_OVERLORDTRANSPORT: return { UNIT_TYPEID::ZERG_OVERLORD };
		case UNIT_TYPEID::ZERG_OVERSEER: return { UNIT_TYPEID::ZERG_OVERLORD, UNIT_TYPEID::ZERG_OVERLORDTRANSPORT };
		case UNIT_TYPEID::PROTOSS_PHOENIX: return { UNIT_TYPEID::PROTOSS_STARGATE };
		case UNIT_TYPEID::PROTOSS_PHOTONCANNON: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_PLANETARYFORTRESS: return { UNIT_TYPEID::TERRAN_COMMANDCENTER };
		case UNIT_TYPEID::PROTOSS_PROBE: return { UNIT_TYPEID::PROTOSS_NEXUS };
		case UNIT_TYPEID::PROTOSS_PYLON: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::ZERG_QUEEN: return { UNIT_TYPEID::ZERG_HATCHERY, UNIT_TYPEID::ZERG_HIVE, UNIT_TYPEID::ZERG_LAIR };
		case UNIT_TYPEID::ZERG_RAVAGER: return { UNIT_TYPEID::ZERG_ROACH };
		case UNIT_TYPEID::TERRAN_RAVEN: return { UNIT_TYPEID::TERRAN_STARPORT };
		case UNIT_TYPEID::TERRAN_REAPER: return { UNIT_TYPEID::TERRAN_BARRACKS };
		case UNIT_TYPEID::TERRAN_REFINERY: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::ZERG_ROACH: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::ZERG_ROACHWARREN: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::PROTOSS_ROBOTICSBAY: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_SCV: return { UNIT_TYPEID::TERRAN_COMMANDCENTER, UNIT_TYPEID::TERRAN_ORBITALCOMMAND, UNIT_TYPEID::TERRAN_PLANETARYFORTRESS };
		case UNIT_TYPEID::TERRAN_SENSORTOWER: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::PROTOSS_SENTRY: return { UNIT_TYPEID::PROTOSS_GATEWAY, UNIT_TYPEID::PROTOSS_WARPGATE };
		case UNIT_TYPEID::PROTOSS_SHIELDBATTERY: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_SIEGETANK: return { UNIT_TYPEID::TERRAN_FACTORY };
		case UNIT_TYPEID::ZERG_SPAWNINGPOOL: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::ZERG_SPINECRAWLER: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::ZERG_SPIRE: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::ZERG_SPORECRAWLER: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::PROTOSS_STALKER: return { UNIT_TYPEID::PROTOSS_GATEWAY, UNIT_TYPEID::PROTOSS_WARPGATE };
		case UNIT_TYPEID::PROTOSS_STARGATE: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_STARPORT: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::TERRAN_SUPPLYDEPOT: return { UNIT_TYPEID::TERRAN_SCV };
		case UNIT_TYPEID::ZERG_SWARMHOSTMP: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::PROTOSS_TEMPEST: return { UNIT_TYPEID::PROTOSS_STARGATE };
		case UNIT_TYPEID::PROTOSS_TEMPLARARCHIVE: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::TERRAN_THOR: return { UNIT_TYPEID::TERRAN_FACTORY };
		case UNIT_TYPEID::PROTOSS_TWILIGHTCOUNCIL: return { UNIT_TYPEID::PROTOSS_PROBE };
		case UNIT_TYPEID::ZERG_ULTRALISK: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::ZERG_ULTRALISKCAVERN: return { UNIT_TYPEID::ZERG_DRONE };
		case UNIT_TYPEID::TERRAN_VIKINGFIGHTER: return { UNIT_TYPEID::TERRAN_STARPORT };
		case UNIT_TYPEID::ZERG_VIPER: return { UNIT_TYPEID::ZERG_LARVA };
		case UNIT_TYPEID::PROTOSS_VOIDRAY: return { UNIT_TYPEID::PROTOSS_STARGATE };
		case UNIT_TYPEID::PROTOSS_WARPPRISM: return { UNIT_TYPEID::PROTOSS_ROBOTICSFACILITY };
		case UNIT_TYPEID::TERRAN_WIDOWMINE: return { UNIT_TYPEID::TERRAN_FACTORY };
		case UNIT_TYPEID::PROTOSS_ZEALOT: return { UNIT_TYPEID::PROTOSS_GATEWAY, UNIT_TYPEID::PROTOSS_WARPGATE };
		case UNIT_TYPEID::ZERG_ZERGLING: return { UNIT_TYPEID::ZERG_LARVA };
		default: return {};
		}
	}
}

